// Generated file. Do not edit.
// This file is generated by the iFlutter

// ignore_for_file: constant_identifier_names
// ignore_for_file: lines_longer_than_80_chars
class AssetsRes {
  AssetsRes._();

  static const String PROJECT_NAME = 'skakone';
  static const String PROJECT_VERSION = '1.0.0+1';
  static const String LOGIN_BG = 'assets/login_bg.jpeg';
  static const String LOGO = 'assets/logo.png';
  static const String LOGO_NO_BG = 'assets/logo_no_bg.png';
  static const String LOGO_NO_DESC = 'assets/logo_no_desc.png';
  static const String PERSON = 'assets/person.jpg';
  static const String UNDRAW_CERTIFICATION_RE_IFLL = 'assets/undraw_certification_re_ifll.svg';
  static const String UNDRAW_EDUCATOR_RE_S3JK = 'assets/undraw_educator_re_s3jk.svg';
  static const String UNDRAW_ONLINE_LEARNING_RE_QW08 = 'assets/undraw_online_learning_re_qw08.svg';
}
